### PR TITLE
Fix initial US keyboard build (fix #18)

### LINKED ISSUE #18: autobuild.sh complete aborts in ./buildUEFI64
Originally reported by @davidepic91 in [this comment](https://github.com/Drive-Trust-Alliance/sedutil/issues/159#issuecomment-315316856).

Error message:
`./buildUEFI64: line 39: scratch/buildroot/PBA64/overlay/etc/init.d/rcS: No such file or directory`

### PR DESCRIPTION
**Pull request by OliverO2**

### CODE REVIEW

**Review by cristim — APPROVED** [review]
@OliverO2 Many thanks for this fix!

**Comment by cristim** [comment]
@OliverO2 please submit this to the upstream DTA repo, this fork is now obsolete after DTA resumed development in the open.

**Comment by OliverO2** [comment]
Hi @cristim, I have no intentions to sign the DTA contributor agreement (too complicated, too far-reaching), so I'm not going to submit my patches there.

**Comment by cristim** [comment]
@OliverO2 If there are enough people who are reluctant to sign the CLA, we can keep running this project as a fork.

Running a fork takes time and effort to maintain, and it only scales if there are enough people to maintain it and , you're the only one so far to ask about this.

**Pull request merged**
