### PR TITLE
Enable incremental builds, add support for non-US keyboards

### LINKED ISSUE #9: Incremental builds
The build process used for generating PBA images is cleaning up downloaded files and rebuilding from scratch all the time, which is often overkill and slower than it should be.

At least the downloaded files should be kept for subsequent uses.

### PR DESCRIPTION
**Pull request by OliverO2**
This pull request fixes #9 and also includes support for keyboard maps in the Rescue and PBA images.

For instructions, see [images/README.md](https://github.com/OliverO2/sedutil/blob/a4d9d16ec5f606fdd08773a19238a01f6299ba1e/images/README.md).

### CODE REVIEW

**Review by cristim — APPROVED** [review]
Thanks for this contribution, it solves some serious pain points

**Comment by cristim** [comment]
@OliverO2 please submit this to the upstream DTA repo, this fork is now obsolete after DTA resumed development in the open.

**Comment by OliverO2** [comment]
Hi @cristim, I have no intentions to sign the DTA contributor agreement (too complicated, too far-reaching), so I'm not going to submit my patches there.

**Comment by cristim** [comment]
Okay, then we need to rebase this on the DTA upstream code.

**Pull request merged**
